# Generated by Django 2.0.1 on 2018-01-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_data', models.CharField(blank=True, max_length=200, null=True, verbose_name='测试数据')),
                ('ts_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('umobile', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='手机号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('uname', models.CharField(blank=True, max_length=18, null=True, verbose_name='用户名')),
                ('unickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('uage', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('usex', models.CharField(default='男', max_length=5, verbose_name='性别')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='testdata',
            name='ts_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_user.UserInfo'),
        ),
    ]
