# Generated by Django 2.0.1 on 2018-01-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='style',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='title',
        ),
        migrations.AddField(
            model_name='snippet',
            name='password',
            field=models.CharField(default=1, max_length=20, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='uage',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='uheadimg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='umobile',
            field=models.CharField(default=2, max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='uname',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='unickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='usex',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
    ]
