# Generated by Django 2.0.1 on 2018-01-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='ts_data',
            field=models.CharField(default=1, max_length=200, verbose_name='测试数据'),
            preserve_default=False,
        ),
    ]
