# Generated by Django 2.0.1 on 2018-01-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_user', '0002_auto_20180115_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('umobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('uname', models.CharField(blank=True, max_length=18, null=True, verbose_name='用户名')),
                ('unickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('uage', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('usex', models.BooleanField(default=True, verbose_name='性别')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
