# Generated by Django 2.0.1 on 2018-01-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_user', '0004_auto_20180115_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='usex',
            field=models.CharField(default='1', max_length=5, verbose_name='性别'),
        ),
    ]
