# Generated by Django 2.0.1 on 2018-01-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_user', '0005_auto_20180115_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='usex',
            field=models.CharField(default='男', max_length=5, verbose_name='性别'),
        ),
    ]
